<a href="https://colab.research.google.com/github/HunRajveer/Numpy/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = [[1,2,3,234],[1,2,4,3],[1,3,2,4]]
# shape while return number of rows and columns
arr = np.array(arr)
print(arr.shape)
# .ndim will give dimansion
print(f'dimension of array is {arr.ndim}')
# .size will return number of element
(f'element are {arr.size}')
# .dtypes return dat type of array
print(f'data type of arr is {arr.dtype}')

(3, 4)
dimension of array is 2
data type of arr is float64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
# in indexing we can take single element from specific position but in slicing we can take multiple element
arr = np.array([10,20,30,40,50])
print(arr[3])

40


Now lets see the 2D indexing aswell

In [ ]:
arr = [[1,2,3,234],[1,2,4,3],[1,3,2,4]]
arr = np.array(arr)
# indexing arr[row,col]
print(arr[1,2])
# slicing arr[start,stop,step :start,stop,step] [row :column]
print(arr[1:3,1:2])




4
[[2]
 [3]]


Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
import numpy as np
arr = [[1,2,3,234],[1,2,4,3],[1,3,2,4]]

arr = np.array(arr)
print(arr[1:3,2:4])
arr

[[4 3]
 [2 4]]


array([[  1,   2,   3, 234],
       [  1,   2,   4,   3],
       [  1,   3,   2,   4]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr>=5)
print(arr[arr>=5])

[False False False False  True  True  True  True  True False]
[5 6 7 8 9]


In [ ]:
arr = np.arange(12)
arr1  = arr.reshape(3,4)
for i in arr1:
  if arr1[i] == 'int64':



dtype('int64')

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
import numpy as np

# Create a 1D array with 12 elements
arr = np.arange(12)
print("Original 1D array:", arr)

# Reshape to 3 rows and 4 columns
# Note: 3 * 4 must equal 12
reshaped_arr = arr.reshape(3, 4)
print("Reshaped 2D array (3x4):\n", reshaped_arr)