<a href="https://colab.research.google.com/github/HunRajveer/Numpy/blob/main/numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
# in numpy array is bit fast then python list and we can perform fast and quick operation , it is memory effecient
import numpy as np
arr = [1,2,3,4,5]
a = np.array(arr)
b = np.arange(5,10)
a
b
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(b//a)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]
[      1      64    2187   65536 1953125]
[5 3 2 2 1]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
# broadcasting is nothing but we will directly apply operation on our array or matrix
a +5
b-1
a**2
b//2
c = np.arange(1,13).reshape(3,4)
c
c*3
c//2
# so this is ow we can apply broadcasting in array

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
# deep copy and shallow copy
#when we perform slicing in array and then broadcast or perfrom any other operation it will not affecgt the original array insted it will creat a copy inside the RAM
#eg
d = np.arange(1,15)
x = d[0:7]
x

array([1, 2, 3, 4, 5, 6, 7])

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
d # d remain unchange so this is shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# deep copy is usually happen in list but we we want to create deep copy for numpy array thern we need to pass the location
e=d
e = e*5
e

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [ ]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[6,7],[8,9]])
# this will work A@B
# this will also work np.dot(A,B)
# T  = transpose it will convert rows into cols and cols into row
# C = A.T
C =B.T
C

array([[6, 8],
       [7, 9]])

In [ ]:
# STAKING
# imp : in stacking we nned to use vactors not matrix
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
np.vstack((a,b)) # it will stack vertically ek ke uper ek , we need to pass it in tuple form
np.hstack((a,b))
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
# Splitting
a= np.arange(16).reshape(4,4)
#print(a)
c= np.vsplit(a,4)
#print(np.hsplit(a,4))
for i in c:

  print(i)

TypeError: only integer scalar arrays can be converted to a scalar index